# Generated by Django 4.2.3 on 2023-07-29 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auxilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField()),
                ('hora_retirada', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data Devolução')),
                ('hora_devolucao', models.TimeField(blank=True, null=True, verbose_name='Hora Devolução')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('emprestado', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=250)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='Masculino', max_length=15)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('raca', models.CharField(choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Não informado', 'Não informado')], default='Não informado', max_length=20, verbose_name='Raça')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=9, verbose_name='RG')),
                ('orgao_expedidor', models.CharField(blank=True, max_length=300, null=True, verbose_name='Orgão expedidor')),
                ('cartao_sus', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cartão SUS')),
                ('nome_mae', models.CharField(max_length=150, verbose_name='Nome da mãe')),
                ('conjuge', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cônjuge')),
                ('profissao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profissão')),
                ('casa_propria', models.BooleanField(default=False, verbose_name='Casa própria')),
                ('outros_casos', models.BooleanField(default=False)),
                ('composicao_familiar', models.PositiveIntegerField(verbose_name='Composição familiar')),
                ('renda_familiar', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Renda familiar')),
                ('vulnerabilidade_social', models.BooleanField(default=False, verbose_name='Vulnerabilidade social')),
                ('observacao_renda', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observação')),
                ('metastase', models.BooleanField(default=False, verbose_name='Metástase')),
                ('descricao_metastase', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização metástase')),
                ('diabetes', models.BooleanField(default=False)),
                ('referencia_doenca', models.CharField(default='', max_length=150, verbose_name='Referência hospitalar')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número')),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de referência')),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(verbose_name='Data de cadastro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.cidade')),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.doenca', verbose_name='Diagnóstico')),
            ],
        ),
        migrations.CreateModel(
            name='SuplementoAlimentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAuxilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('abreviacao', models.CharField(max_length=5, verbose_name='Abreviação')),
            ],
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=9)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'responsáveis',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_auxilio_aprovado',
            field=models.ManyToManyField(blank=True, to='pacientes.tipoauxilio'),
        ),
    ]
