# Generated by Django 4.2.3 on 2023-08-04 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.tipoconsulta'),
        ),
        migrations.AddField(
            model_name='auxilio',
            name='equipamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='pacientes.equipamento'),
        ),
        migrations.AddField(
            model_name='auxilio',
            name='medicamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='pacientes.medicamento'),
        ),
        migrations.AddField(
            model_name='auxilio',
            name='paciente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auxilios', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='auxilio',
            name='suplemento_alimentar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suplementos', to='pacientes.suplementoalimentar'),
        ),
        migrations.AddField(
            model_name='auxilio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.tipoauxilio'),
        ),
    ]
